maitag_app/urls.py
from django.urls import path  

from .views import (
    UtteranceList, 
    UtteranceDetail,
    IntentList,
    IntentDetail,
    LabelInstanceList,
    LabelInstanceDetail,
    MLModelList,
    MLModelDetail,
    ClassifierList,
    ClassifierDetail,
    ProjectList,
    ProjectDetail,
    Label,
)



app_name = 'maitag_app'

urlpatterns = [
    path('utterances/', UtteranceList.as_view(), name = 'utterance-list'),
    path('utterances/<int:pk>/', UtteranceDetail.as_view(), name = 'utterance-detail'),
    path('intents/', IntentList.as_view(), name = 'intent-list'),
    path('intents/<int:pk>/', IntentDetail.as_view(), name = 'intent-detail'),
    path('labels/', LabelInstanceList.as_view(), name = 'label-list'),
    path('labels/<int:pk>/', LabelInstanceDetail.as_view(), name = 'label-detail'),
    path('mlmodels/', MLModelList.as_view(), name = 'mlmodel-list'),
    path('mlmodels/<int:pk>/', MLModelDetail.as_view(), name = 'mlmodel-detail'),   
    path('classifiers/', ClassifierList.as_view(), name = 'classifier-list'),
    path('classifiers/<int:pk>/', ClassifierDetail.as_view(), name = 'classifier-detail'), 
    path('projects/', ProjectList.as_view(), name = 'project-list'),
    path('projects/<int:pk>/', ProjectDetail.as_view(), name = 'project-detail'),
    path('label/', Label.as_view(), name = 'label-utterance'),
]

maitag_site/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from maitag_app import views



urlpatterns = [
    path('', views.home, name = 'home'),
    path('admin/', admin.site.urls),
    path('api/', include('users.urls', namespace = 'users')),
    path('api/maitag/', include('maitag_app.urls', namespace = 'maitag_app'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include

from .views import (
    CustomUserList, 
    ProfileList, 
    RegisterView,
    ResetPasswordRequest,
    activate_reset
)



app_name = 'users'

urlpatterns = [
    path('', include('dj_rest_auth.urls')), 
    path('users/', CustomUserList.as_view(), name = 'users-list'),
    path('profiles/', ProfileList.as_view(), name = 'profiles-list'),
    path('register/', RegisterView.as_view(), name = 'register'),
    path('password-reset-request/', ResetPasswordRequest.as_view(), name = 'password-reset-request'),
    path('password-reset/<uidb64>/<token>/', activate_reset, name = 'password-reset-activate'),
]

maitag_app/models.py
from django.db import models
from users.models import CustomUser
from itertools import chain


class MLModel(models.Model):
    """represents the used machine learning algorithm"""

    name = models.CharField(max_length = 30)
    path = models.CharField(max_length = 256, null = True)

    def __str__(self):
        return self.name


class Classifier(models.Model):
    """represents the tagger"""

    name = models.CharField(max_length = 30)
    mlmodel = models.ForeignKey(MLModel, on_delete = models.CASCADE)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.name

class Intent(models.Model):

    name = models.CharField(max_length = 30)

    def __str__(self):
        return self.name


class LabelInstance(models.Model):
    """represents massage tag (intent)"""

    intent = models.ForeignKey(Intent, null = True, on_delete = models.CASCADE)
    description = models.TextField()
    classifier = models.ForeignKey(Classifier, null = True, on_delete = models.CASCADE)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.description


class Utterance(models.Model):
    """represents user messages"""

    user = models.ForeignKey(CustomUser, on_delete = models.CASCADE)
    text = models.TextField()
    intents = models.ManyToManyField(Intent, blank = True)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.text


class Project(models.Model):

    project_id = models.CharField(max_length = 256, null = True)
    utterance_id = models.CharField(max_length = 256, null = True)
    utterance = models.CharField(max_length = 256)
    label = models.CharField(max_length = 100, null = True)
    confidence = models.IntegerField(null = True)

    def __str__(self):
        return self.utterance

maitag_app/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse
from rest_framework import generics
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView

from .models import (
    Utterance, 
    Intent, 
    LabelInstance, 
    MLModel, 
    Classifier, 
    Project
)
from .ml import *
from .serializers import (
    UtteranceSerializer, 
    IntentSerializer, 
    LabelInstanceSerializer,
    MLModelSerializer,
    ClassifierSerializer,
    ProjectSerializer
)



def home(request):
    return render(request, 'maitag_app/home.html')


class MLModelList(generics.ListCreateAPIView):

    queryset = MLModel.objects.all()
    serializer_class = MLModelSerializer


class MLModelDetail(generics.RetrieveUpdateDestroyAPIView):

    queryset = MLModel.objects.all()
    serializer_class = MLModelSerializer  


class ClassifierList(generics.ListCreateAPIView):

    queryset = Classifier.objects.all()
    serializer_class = ClassifierSerializer


class ClassifierDetail(generics.RetrieveUpdateDestroyAPIView):

    queryset = Classifier.objects.all()
    serializer_class = ClassifierSerializer


class IntentList(generics.ListCreateAPIView):

    queryset = Intent.objects.all()
    serializer_class = IntentSerializer


class IntentDetail(generics.RetrieveUpdateDestroyAPIView):

    queryset = Intent.objects.all()
    serializer_class = IntentSerializer


class LabelInstanceList(generics.ListCreateAPIView):

    queryset = LabelInstance.objects.all()
    serializer_class = LabelInstanceSerializer


class LabelInstanceDetail(generics.RetrieveUpdateDestroyAPIView):

    queryset = LabelInstance.objects.all()
    serializer_class = LabelInstanceSerializer


class UtteranceList(generics.ListCreateAPIView):

    queryset = Utterance.objects.all()
    serializer_class = UtteranceSerializer


class UtteranceDetail(generics.RetrieveUpdateDestroyAPIView):

    queryset = Utterance.objects.all()
    serializer_class = UtteranceSerializer



class ProjectList(generics.ListAPIView):

    queryset = Project.objects.all()
    serializer_class = ProjectSerializer   


class ProjectDetail(generics.RetrieveAPIView):

    queryset = Project.objects.all()
    serializer_class = ProjectSerializer


def predict_unknown_label(utterance=None, **kwargs):
    """label unknown utterance intent using clustering 

    >>> predict_unknown_label(utterance="text never seen before")
    {'label': 'text', ...}
    """
    answer = {
        "label": utterance.split()[0],
        "confidence": 1.0,
    }
    return answer


class Label(generics.CreateAPIView):

    queryset = Project.objects.all()
    serializer_class = ProjectSerializer

    def post(self, request):
        serializer = ProjectSerializer(data = request.data)
        if serializer.is_valid():
            serializer.save()
            utterance = serializer.data['utterance']
            predictions = predict_labels(utterance)
            data = {
                "project_id": serializer.data['project_id'],
                "utterance_id": serializer.data['utterance_id'],
                "utterance": utterance,
                "label": predictions['label'],
                "confidence": round(predictions['confidence'], 2)
            }
            if data['label'] == 'unknown':
                data_update = predict_unknown_label(**data)
                data.update(data_update)
            return Response(data, status = status.HTTP_200_OK)
        return Response(serializer.errors, status = status.HTTP_400_BAD_REQUEST)




""" Concrete View Classes
# CreateAPIView
Used for create-only endpoints.
# ListAPIView
Used for read-only endpoints to represent a collection of model instances.
# RetrieveAPIView
Used for read-only endpoints to represent a single model instance.
# DestroyAPIView
Used for delete-only endpoints for a single model instance.
# UpdateAPIView
Used for update-only endpoints for a single model instance.
# ListCreateAPIView
Used for read-write endpoints to represent a collection of model instances.
RetrieveUpdateAPIView
Used for read or update endpoints to represent a single model instance.
# RetrieveDestroyAPIView
Used for read or delete endpoints to represent a single model instance.
# RetrieveUpdateDestroyAPIView
Used for read-write-delete endpoints to represent a single model instance.
"""

maitag_app/templates/maitag_app/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset = "utf-8">
    <meta name = "viewport" content = "width=device-width, initial-scale=1, shrink-to-fit=no">
    <title> MAITAG </title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- Local CSS -->
    <link rel = "stylesheet" type = "text/css" href = "{% static 'maitag_app/style.css' %}">  
  </head>
  <body>
    {% if user.is_authenticated %}
      <header>
        <nav class = "navbar navbar-expand-lg bg-dark navbar-dark py-3 fixed-top">
          <div class = "container">
            <a href = "{% url 'home' %}" class = "navbar-brand fw-bold"> [ MAITAG ] </a>
            <button
            class = "navbar-toggler"
            type = "button"
            data-bs-toggle = "collapse"
            data-bs-target = "#navmenu"
            >
            <span class = "navbar-toggler-icon"></span>
            </button>

            <div class = "collapse navbar-collapse" id = "navmenu">
              <ul class = "navbar-nav ms-auto">
                  <a href = "{% url 'users:rest_logout' %}"> 
                      <button class = "btn btn-outline-light"> Logout </button>
                  </a>
              </ul>
            </div>
          </div>
        </nav>
      </header>
    {% else %}
      <header>
        <nav class = "navbar navbar-expand-lg bg-dark navbar-dark py-3 fixed-top">
          <div class = "container">
            <a href = "{% url 'home' %}" class = "navbar-brand fw-bold"> [ MAITAG ] </a>
            <button
            class = "navbar-toggler"
            type = "button"
            data-bs-toggle = "collapse"
            data-bs-target = "#navmenu"
            >
            <span class = "navbar-toggler-icon"></span>
            </button>

            <div class = "collapse navbar-collapse" id = "navmenu">
              <ul class = "navbar-nav ms-auto">
                  <li class = "nav-item me-3">
                      <a href = "{% url 'users:register' %}" class = "nav-link"> Register </a>
                  </li>
                  <a href = "{% url 'users:rest_login' %}"> 
                      <button class = "btn btn-outline-light"> Login </button>
                  </a>
              </ul>
            </div>
          </div>
        </nav>
      </header>
    {% endif %}
    <main class = "container">
      {% block content %}

      {% endblock %}
      {% if user.is_authenticated %}
      {% else %}
        <div class = "forgot-password">
          <a href = "{% url 'users:password-reset-request' %}"> Forgot password? </a>
        </div>
      {% endif %}
    </main>
    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

maitag_app/templates/maitag_app/home.html
{% extends "maitag_app/base.html" %}



{% block content %}

    <div class = "left-sidebar">

        <div class = "row">
            <div class = "col-lg-2">
                <div class = "content-section">
                    <ul class = "list-group">
                        <a class = "list-group-item list-group-item-light" href = "{% url 'maitag_app:project-list' %}">
                            <span> Projects </span>
                        </a>
                        <a class = "list-group-item list-group-item-light" href = "{% url 'maitag_app:utterance-list' %}">
                            <span> Utterances </span>
                        </a>
                        <a class = "list-group-item list-group-item-light" href = "{% url 'maitag_app:intent-list' %}">
                            <span> Intents </span>
                        </a>
                        <a class = "list-group-item list-group-item-light" href = "{% url 'maitag_app:label-list' %}">
                            <span> Labels </span>
                        </a>
                        <a class = "list-group-item list-group-item-light" href = "{% url 'maitag_app:mlmodel-list' %}">
                            <span> MLModels </span>
                        </a>
                        <a class = "list-group-item list-group-item-light" href = "{% url 'maitag_app:classifier-list' %}">
                            <span> Classifiers </span>
                        </a>
                    </ul>
                </div>
            </div>
            <div class = "col-lg-8">
                <article class = "card">
                    <div class = "card-body">
                        <div class = "row">
                            <div class = "col-lg-10">
                                <h4 class = "text-dark"> 
                                    Machine Assisted Intent Tagging
                                </h4>
                            </div>
                            <div class = "col-lg-2">
                                <span class = "badge bg-success">
                                    <a class = "text-light" href = "https://gitlab.com/tangibleai/maitag/" target = "_blank"> in progress </a>
                                </span>
                            </div>
                        </div>
                        <p class = "card-text text-break">  
                            MAITAG is a collection of Machine learning models and API for natural language intent classification.
                        </p>
                        <a class = "btn btn-dark text-light" href = "{% url 'maitag_app:label-utterance' %}"> 
                            Make a prediction 
                        </a>
                        <p class = "card-text text-break">  
                            Link to the source code on <a href = "https://gitlab.com/tangibleai/maitag/" target = "_blank"> GitLab </a>
                        </p>
                    </div> 
                </article>                 
            </div>
        </div>

    </div>

{% endblock %}